### ISSUE TITLE
The addon doesn't install in kodi 19

### ISSUE THREAD

**Issue by peno64** [add-ons/script.speedtester#11]
It says that it needs Python 2.26.0 which is not there in Kodi 19

**Comment by peno64** [comment]
I looked at the code in addon.py and I see that it supports both Python2 and Python3
Iit is the following line in addon.xml which makes it not installable under kodi 19
<import addon="xbmc.python" version="3.0.0"/>
So I just removed it and then it installs and runs fine.

**Comment by dagwieers** [comment]
@peno64 I am not going to go into this *again*. Kodi devs decided that Kodi v19 is special and as a result of this we cannot provide a single codebase that works out-of-the-box on Kodi v18 and older, and Kodi v19. This sucks big time and we tried to make Kodi devs understand the impact on Addon developers, but they did not care (read: didn't think this was important).

As long as Kodi v18 is used the most (we have almost no Kodi v19 users) the codebase will work for Kodi v18 out-of-the-box, as soon as Kodi v19 takes over from Kodi v18 in popularity we can decide to change this. But today that makes absolutely no sense.

My preference was that we could support all versions of Kodi with one codebase, but that is out of my control.

**Comment by dagwieers** [comment]
Matrix release files are available from: https://github.com/add-ons/script.speedtester/releases
