### ISSUE TITLE
Extend scale till 100 Mbps

### ISSUE THREAD

**Issue by peno64** [add-ons/script.speedtester#20]
At this moment the speedtest scale goes till 50Mbps and then it stalls. I have with my regular telenet connection more than 70 Mbps and even 80 Mbps sometimes so it would be nice if the scale could be extended.
Maybe even better would be a logaritmic scale that goes till 1000 Mbps ...

**Comment by dagwieers** [comment]
I think this was done on purpose. Everything over 25Mbps is sufficient to do 4K.
If we would have a scale going to 1Gbps, people with only 50Mbps may be thinking their connection is not good enough.

**Comment by peno64** [comment]
You have a point but if it is a logatitmic scale then this would be lesser an issue. Or another solution could be that the scale is not immediately shown but only after a couple of seconds after the speedtest sees what the current speed is.
So it could first only show markers without numbers and then after a couple of seconds show the scale depending of the initial speed.

**Comment by dagwieers** [comment]
I am open to ideas. The current behaviour is how I inherited it, and I am not keen on changing behaviour unless there is a wider consensus.

One thing I do consider erratic behaviour is the gauge not moving more fluidly.
